[tool.black]
line-length = 100
target-version = ['py38']

[tool.isort]
default_section = 'THIRDPARTY'
# Black compatible config
ensure_newline_before_comments = true
force_grid_wrap = 0
include_trailing_comma = true
line_length = 100
multi_line_output = 3
use_parentheses = true
